name: Hi Today 
  
# 触发这个工作流的事件  
on:  
  push:  
    branches: [ main ]  
  
# 定义工作流中的作业  
jobs:  
  # 这个作业的名称是build  
  build:  
    # 作业运行的环境（这里使用Ubuntu最新稳定版）  
    runs-on: ubuntu-latest  
  
    # 作业中的步骤  
    steps:  
      # 第一步：检出仓库代码  
      - name: Checkout  
        uses: actions/checkout@v2  
  
      # 第二步：打印一条消息  
      - name: Print a greeting  
        run: |  
          echo 'Hello, world!'  
          echo 'This is a test of GitHub Actions!'
